# Database connection properties cho PostgreSQL trên Render
spring.datasource.url=jdbc:postgresql://dpg-da2o6b7lk1mc73cjgd20-a.singapore-postgres.render.com:5432/hopitalwebsite?sslmode=require
spring.datasource.username=huy
spring.datasource.password=LtTh5AxK4bkKK6LBEIJcuxpg8IDnbnIm
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate properties cho PostgreSQL
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Server port (optional, default is 8080)
server.port=8080

# Character Encoding for HTTP requests and responses
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true
spring.http.encoding.charset=UTF-8
spring.http.encoding.force=true

# JWT Properties
app.jwt-secret=daf21898c5344a849795a3b32c11e39200a139a74228a68e62d2d1f251d76853
app.jwt-expiration-milliseconds=86400000