# C:/Users/acer/IdeaProjects/Hopital application/src/main/resources/application.properties
# Database connection properties
# Thêm characterEncoding=UTF-8 để hỗ trợ tiếng Việt
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=hospital_db;encrypt=false;trustServerCertificate=true;characterEncoding=UTF-8
spring.datasource.username=huy
spring.datasource.password=123123
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# JPA/Hibernate properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

# Server port (optional, default is 8080)
server.port=8080

# Character Encoding for HTTP requests and responses
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true
spring.http.encoding.charset=UTF-8
spring.http.encoding.force=true

# JWT Properties
app.jwt-secret=daf21898c5344a849795a3b32c11e39200a139a74228a68e62d2d1f251d76853
app.jwt-expiration-milliseconds=86400000
